#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/dphys-swapfile 20100506-2\~\~ -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/dphys-swapfile" ] ; then
	chmod +x "/etc/init.d/dphys-swapfile" >/dev/null || true
fi
# End automatically added section
